### ISSUE TITLE
Unnecessary `del` in federated GAN code?

### ISSUE THREAD

**Issue by BjarnePfitzner** [google-research/federated#11]
This is more a comment than an issue, but I was looking through the federated GAN code and found a piece of code that surprised me:

In [/gans/experiments/emnist/train.py:348-350](https://github.com/google-research/federated/blob/95c36d9d072f61da16f395a1c2b843bd3aed2582/gans/experiments/emnist/train.py#L348) (and similarly in 352-364) the following function is defined:
```python
def server_gen_inputs_fn(round_num):
    del round_num
    return next(server_gen_inputs_iterator)
```
What is the purpose of round_num being passed as an argument (by value) when the first line of code inside the function deletes it?

**Comment by jvmncs** [comment]
This is an artifact of Google's Python style guide. See the last few paragraphs at this link https://google.github.io/styleguide/pyguide.html#214-decision
