### ISSUE TITLE
`get_model_weights` not yet available in TFF

### ISSUE THREAD

**Issue by zehao-sean-huang** [google-research/federated#13]
Hi,

I was using the compression folder to understand some basics of TensorFlow Federated. It turns out I was blocked by this error and didn't seem to figure out a solution. 

```
Traceback (most recent call last):
  File "run_experiment.py", line 245, in <module>
    app.run(main)
  File "/data/zehaohuang/anaconda/envs/fetchsgd/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/data/zehaohuang/anaconda/envs/fetchsgd/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_experiment.py", line 241, in main
    run_experiment()
  File "run_experiment.py", line 233, in run_experiment
    **training_loop_dict)
  File "/home/eecs/zehaohuang/federated/utils/training_loop.py", line 195, in run
    _check_iterative_process_compatibility(iterative_process)
  File "/home/eecs/zehaohuang/federated/utils/training_loop.py", line 128, in _check_iterative_process_compatibility
    raise compatibility_error
utils.training_loop.IterativeProcessCompatibilityError: The iterative_process argument must be of type`tff.templates.IterativeProcess`, and must have an attribute `get_model_weights`, which must be a `tff.Computation`. This computation must accept as input the state of `iterative_process`, and its output must be a nested structure of tensors matching the input shape of `validation_fn`.
```

The command I used was the one suggested in the README file of the `compression` folder:

```bash
python3 run_experiment.py --client_optimizer=sgd --client_learning_rate=0.2 --server_optimizer=sgd --server_learning_rate=1.0 --use_compression=True --broadcast_quantization_bits=8 --aggregation_quantization_bits=8 --use_sparsity_in_aggregation=True
```

Is there a way to work around this?

**Comment by PraChetit** [comment]
Ah, this seems to be expecting a slight change which was may or may not be in the latest release of TFF. What TFF version do you have? If updating TFF version does not help, you can 
a) Use TFF directly from source, not the pip release or
b) After creating `iterative_process` [here](https://github.com/google-research/federated/blob/8f344a80b91d5172aeb6dbd35a674a80795eeb4a/compression/run_experiment.py#L219), add [these](https://github.com/tensorflow/federated/blob/b82dd1a38789d501443a8d20f4345dbd9310db7a/tensorflow_federated/python/learning/federated_averaging.py#L243-L247) lines to manually add the expected `get_model_weights` attribute.

**Comment by zcharles8** [comment]
To piggyback off of @PraChetit's comment: We generally recommend either building TFF from source, or depending on the nightly pip package. Since this directory houses evolving research, it often uses recent changes on the TFF GitHub that are not reflected in the latest stand-alone version.

**Comment by zcharles8** [comment]
@zehao-sean-huang Were you able to get this working?

**Comment by zehao-sean-huang** [comment]
So sorry for the late reply. Yes! We were able to get it working after switching to nightly builds. With the help of the script, we implemented our own compression algorithm successfully with TFF and started running experiments with it. Thanks for the help.

**Comment by zcharles8** [comment]
That's great news! Glad to hear it.
