### ISSUE TITLE
tff.python.simulation has no attribute "MetricsManager"

### ISSUE THREAD

**Issue by juntang-zhuang** [google-research/federated#15]
I ran into error "tff.python.simulation has no addtribute "MetricsManager"". Could you specify which version of tf and tff did you use? Thanks a lot.

**Comment by wennanzhu** [comment]
Hi,

tff.python.simulation.MetricsManager is in the current stable tff version 0.17.0 

Could you try this version and see if the error still appears?

**Comment by nightldj** [comment]
MetricsManager is moved from this repo to TFF in https://github.com/tensorflow/federated/commit/b05b64588b2e6b6e078f6d681efb5cd3148e8d4f.

We suggest install TFF nightly https://pypi.org/project/tensorflow-federated-nightly/ to run code in this repo.

**Comment by zcharles8** [comment]
@juntang-zhuang Were you able to get this working?

**Comment by juntang-zhuang** [comment]
@zcharles8 Sorry for the late reply. It works now. Thanks for the help.
