### ISSUE TITLE
Computing epsilon

### ISSUE THREAD

**Issue by Henrique-Potter** [google-research/federated#18]
Hi, I know that this is a work in progress but, I am curious about how we can compute epsilon for this implementation of DP for federated learning.

Is it possible to use the compute epsilon proposed here (https://arxiv.org/abs/1908.10530) for the federated model?

**Comment by galenmandrew** [comment]
Yes, RDP can be computed using the functions here:

https://github.com/tensorflow/privacy/blob/master/tensorflow_privacy/privacy/analysis/rdp_accountant.py

**Comment by Henrique-Potter** [comment]
I see. Is there an example of how to use it with a federated model with the DP query (tff.utils.build_dp_query) as the aggregation process? I could only find examples for "locally" trained models (e.g., https://github.com/tensorflow/privacy/tree/master/tutorials).

For example, will the parameter T "steps" be the number of rounds from federated model training?

**Comment by galenmandrew** [comment]
I'm not sure about a public example I can point you to, but it works the same whether local or federated. T would be number of rounds, and q would be sampling ratio (clients per round / total clients).

**Comment by Henrique-Potter** [comment]
No problem.  
My issue is that I am getting quite big ep spent per round. I know that for the MNIST example the target delta is 1e-5. What will be the target delta in a fed model? Will it be proportional to the number of data points from a single client or to all the data points from all users? 

So for example here (code from [here](https://github.com/tensorflow/privacy/blob/master/tutorials/mnist_dpsgd_tutorial_keras.py)).

`    """Computes epsilon value for given hyperparameters."""
    if noise_multi == 0.0:
        return float('inf')

    # This probably are the alphas
    orders = [1 + x / 10. for x in range(1, 100)] + list(range(12, 64))

    rdp = compute_rdp(
      q=user_ratio,
      noise_multiplier=noise_multi,
      steps=steps,
      orders=orders)

    return get_privacy_spent(orders, rdp, target_delta=delta)[0]`

So with:
- step of 1 (first round)
- 10 subsample from 400 clients (q=0.025), 
- noise of 0.3 
- target delta of 1e-5 

I get 15.05. Even if my target delta is lower the ep spent is still high. It seems that I need much more noise, more clients, or smaller subsampling.

-> Thanks for the help. I am a Ph.D. student and started working with DP.

**Comment by galenmandrew** [comment]
Typically delta is chosen to be no larger than 1/n for n clients. So with 400 clients you could take it up a bit. However your larger problem is that you cannot get good privacy with only 400 clients. To get single digit epsilon you may need an order of magnitude higher clients per round and two orders higher total clients. I suggest you play around with get_privacy_spent to see how it changes with respect to each of those parameters. If this is for research purposes, you could present results with a given noise level that has a high epsilon, and then rely on the fact that if hypothetically you could scale up clients per round (keeping q constant, which means also scaling up total clients) and scale up noise proportionally, you would most likely train a model with similar utility but higher privacy.

**Comment by Henrique-Potter** [comment]
I see. Thank you very much.
