### ISSUE TITLE
CIFAR10 experiment in Adaptive Federated Optimization

### ISSUE THREAD

**Issue by pedropgusmao** [google-research/federated#19]
Hi there,
I'm trying to reproduce the CIFAR10 experiment in "Adaptive Federated Optimization", but I am not sure which dirichlet concentration value to use. I see in https://github.com/google-research/federated/blob/f0ff19d0a5020b6623be1de73a6bab48822c182f/utils/datasets/cifar10_dataset.py#L33 that the `dirichlet_parameter` is set to `1`, and that calls to `load_cifar10_federated()` do not change that parameter. However, I see in the paper (Appendix C.2) that the dirichlet parameter is set to `0.1`. Could you please clarify which value should be used as input to the numpy dirichlet function that will allow for reproducibility? Thanks in advance.

**Comment by zcharles8** [comment]
Hi @pedropgusmao. As the paper says, `0.1` is what you should use for reproducibility. However, there is currently randomness in the data partitioning that will make the experiments not 100% reproducible (though it should be comparable).

If you want to exactly reproduce, I recommend the CIFAR-100 experiments, as the dataset has been saved in its entirety here: https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/cifar100

**Comment by pedropgusmao** [comment]
Thanks @zcharles8 !
