### ISSUE TITLE
what is the recommended usage?

### ISSUE THREAD

**Issue by amitport** [google-research/federated#2]
I'm a little confused.

I was hoping I could just `git submodule` this or `pip install tff-research` or  `pip install -e git+https://github.com/google-research/federated`. 

Could you share the intended installation process?  (for example how to use just utils in this project?) (I could use with some ugly hacks, but I rather there was a direct way, preferably without having to build everything with bazel)

**Comment by nightldj** [comment]
Hi @amitport, this repository is not intended to be a pip package, but instead a collection of research projects. The current usage is probably fork or `git clone` or similar.

I do think `utils` is special and deserves different treatment for usage.  I will update later on what we can do to help. Thanks!

**Comment by amitport** [comment]
@nightldj thanks.

I'm may have additional research that I want to expand on something here. currently, it seems that the python packages here do not have any root project so I will need to copy files and change imports,
(if that's not the case, I appreciate if you could explain what happen after the `git clone` and how changes can be tracked)

I mean, why not put all the code folders inside of a `tensorflow_federated_reseach` folder and add a simple setup.py? I can try and submit a PR if it sounds reasonable. (so instead of importing `utils` the import will be from `tensorflow_federated_reseach.utils` etc.,)

**Comment by amitport** [comment]
if anyone is interested I maintain a fork with imports prefixed by `google_tff_research` (and load it as a submodule)

https://github.com/amitport/google_tff_research/tree/95fabb16c7e663185ea0b3c07035718f05e8c732`

**Comment by michaelreneer** [comment]
@amitport What is missing for you to simply use a `git submodule`? Seems like maybe we can add some `__init__.py` files to give you access to the utils directory, no?

**Comment by amitport** [comment]
I have my own workflow, which is maybe unnecessarily hacky, so I don't think it will be helpful to get into the details. I'm not a python expert so I'm trying to understand how to use this from ones own separate project.

Specifically, when I load to source into some folder, should I add it to PYTHONPATH? every subfolder separably? even though this would work, it's kind of ugly and I was hoping that there is another way

**Comment by michaelreneer** [comment]
Yeah so in my mind the intended use is to simply use a submodule. I have constructed an example experiment here https://github.com/michaelreneer/experiment

In this case you can see that I am not using `Bazel` or anything except for Python and git. Here is how you can test...

```shell
$ git clone https://github.com/michaelreneer/experiment
$ cd experiment
$ git submodule update --init --recursive
$ virtualenv venv
$ source venv/bin/activate
$ pip install absl-py tensorflow
$ ./test.py
```

If you have any trouble please let me know.

[Why we don't need `__init__.py` files](https://stackoverflow.com/questions/37974843/why-can-i-import-successfully-without-init-py)

**Comment by amitport** [comment]
Thanks,
Still, maybe it's a python beginner question, but how do you do something like 'from federated.utils import training_loop'?
(importing a file which imports `utils`)

I can add `federated` folder to PYTHONPATH, I'm just wondering if there is another way.

**Comment by michaelreneer** [comment]
Ah now I understand the issue you are having.

**Comment by michaelreneer** [comment]
I think that would work or I think you can append to `sys.path`. I have updated the example that I linked.

See https://docs.python.org/3/tutorial/modules.html#standard-modules for more information.

**Comment by amitport** [comment]
OK thanks @michaelreneer !
