### ISSUE TITLE
Calculating epsilon budget for the federated model with DPquery

### ISSUE THREAD

**Issue by Henrique-Potter** [google-research/federated#20]
Hi is it possible to get the epsilon budget as an evaluation metric in the example from federated/differential_privacy/stackoverflow/run_federated.py? Or how can you calculate it given the parameters for this fed model using the rdp accountant from  tensorflow_privacy.privacy.analysis.rdp_accountant?

**Comment by galenmandrew** [comment]
Yes, the best way is to use the RDP accountant from tensorflow_privacy. Use whatever noise multiplier you ran with and a sampling fraction q=clients_per_round / n. The epsilon computation is not changed whether you are running DP-FedAvg for user-level DP or DP-SGD for example-level DP. Adaptive clipping also does not change the epsilon.
