### ISSUE TITLE
Data loading is error

### ISSUE THREAD

**Issue by codaibk** [google-research/federated#21]
Hi, 
Thanks for your framework. I tried to run your code but get this error "TypeError: Values of type <label=int32,pixels=float32[28,28]>* cannot be cast to type <pixels=float32[28,28],label=int32>*" when loading emnist data. Do you know how I can fix it? Thanks.

**Comment by ZacharyGarrett** [comment]
Thanks for the report. Could you add which code was being run, and copy-paste the stack trace included with the error message?

**Comment by codaibk** [comment]
Thanks for your reply. I run differential privacy for emnist code. The error is shown in below pict:
![1](https://user-images.githubusercontent.com/28720676/107647164-cf6f7280-6cb5-11eb-83f4-d25fcd6b989b.png)
![2](https://user-images.githubusercontent.com/28720676/107647187-d72f1700-6cb5-11eb-9a54-76ed2614a5e5.png)

**Comment by codaibk** [comment]
@ZacharyGarrett Hi, is there any update?

**Comment by codaibk** [comment]
It seems your original code has typo. It run smoothly after I changed the order of your code in function `get_federated_datasets` of `emnist_dataset.py` file.
I used this one:
`feature_dtypes = collections.OrderedDict(
    label=tff.TensorType(tf.int32),
    pixels=tff.TensorType(tf.float32, shape=(28, 28))
      )`
instead of using your original code:
`feature_dtypes = collections.OrderedDict(
      pixels=tff.TensorType(tf.float32, shape=(28, 28)),
      label=tff.TensorType(tf.int32)
      )`

**Comment by ZacharyGarrett** [comment]
Might commit https://github.com/google-research/federated/commit/bea0484a47fe5ef3cce4c945b36ed93e7f34f06e have fixed this issue?

**Comment by zcharles8** [comment]
@codaibk As @ZacharyGarrett mentioned, commit bea0484a47fe5ef3cce4c945b36ed93e7f34f06e should fix the problem. Can you confirm or deny this?

**Comment by codaibk** [comment]
@zcharles8 ya, I just only changed the `emnist_dataset.py ` and it fix the problem.
