### ISSUE TITLE
bazel test shared:fed_avg_schedule_test doesn't pass tests due to GPU memory usage

### ISSUE THREAD

**Issue by houcharlie** [google-research/federated#26]
Environment: [This docker container](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_20-09.html#rel_20-09) tf-nightly, tff-nightly, GPU: Tesla V100-SXM2 32 GB

I ran bazel test shared:fed_avg_schedule_test and it did not pass the tests because the memory was overused:
[test.log](https://github.com/google-research/federated/files/6103593/test.log)

Was wondering what could be done to get this to work?  Ideally I would want to follow the same testing practices in this repo for my own code and experiments.

I can run 

> bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=100 \
--client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 \
--server_optimizer=sgd --server_learning_rate=1.0 --clients_per_round=10 \
--client_epochs_per_round=1 --experiment_name=emnist_fedavg_experiment

(the original example) just fine.

**Comment by houcharlie** [comment]
For more info, tests work when I run on CPU only.

**Comment by zcharles8** [comment]
Hi @houcharlie. The test you mention is not intended to ensure GPU memory is not overused, especially since it downloads multiple datasets from TFF. It is primarily there so that I can ensure that changes do not break any of the tasks' core logic. As long as it passes on CPU, this is working as intended. Thanks for your interest!

**Comment by zcharles8** [comment]
For context: Both of those tests are passing on the GPU setup that I have been using to test, so somewhere along the line is a GPU configuration or resource issue.

**Comment by houcharlie** [comment]
[test.log](https://github.com/google-research/federated/files/6135550/test.log)
Hey @zcharles8, sorry for the delay.  The test log is attached above if I comment out the test you mentioned earlier.

Interestingly, if I run the test once more, the log changes a bit:
[test_after.log](https://github.com/google-research/federated/files/6135571/test_after.log)

i.e. the memory issues creep in again the second time I run the test.  Furthermore, I found this stackoverflow post: https://stackoverflow.com/questions/43147983/could-not-create-cudnn-handle-cudnn-status-internal-error

which seems to suggest that I should set `export TF_FORCE_GPU_ALLOW_GROWTH='true'` in my .bashrc.  I did so,
[test_3.log](https://github.com/google-research/federated/files/6135575/test_3.log)
and it failed again, with similar messages to the first log.

**Comment by zcharles8** [comment]
Hi @houcharlie. The fact that you're getting inconsistent logs suggests that something might be up with the GPU configuration. If possible, can you try running the following test from the TFF repository: https://github.com/tensorflow/federated/blob/master/tensorflow_federated/python/learning/federated_averaging_test.py

This might help tell us whether the GPU configuration is the issue, as this test is pretty robustly tested on GPU.

**Comment by houcharlie** [comment]
Yeah, I got similar memory errors on the test you just suggested.  I guess it is my GPU configuration, thanks for the help.

**Comment by houcharlie** [comment]
Yeah, I was able to fix this issue by doing

pip install --upgrade -r tensorflow_federated/requirements.txt

on the tensorflow_federated repo, if anyone is looking at this int he future.
