### ISSUE TITLE
"AttributeError: 'GFile' object has no attribute 'readable' "  when try to generate a centralized training benchmark.

### ISSUE THREAD

**Issue by GitDjTHU** [google-research/federated#28]
I used the following to get a centralized training benchmark and facing a GFile attribute error every time after 1st epoch.

```shell
bazel run main:centralized_trainer -- --task=emnist_cr --num_epochs=100 --experiment_name=emnist_central_experiment --centralized_optimizer=sgd --centralized_learning_rate=0.1 --batch_size=64
```
A tf2.4 and tff-nightly environment was used as mention in another issue [NotImplementedError("b/162106885") for Optimization Folder #24](https://github.com/google-research/federated/issues/24).
![image](https://user-images.githubusercontent.com/7446752/110730133-e2e10f80-825a-11eb-8c47-3feb252a0e17.png)

The following pic shows the call stack of this error.

**Comment by GitDjTHU** [comment]
The bug is found. Just simply change the GFile mode in function py.read_csv of utils_impl.py from 'rb' to 'r' will work.

**Comment by alshedivat** [comment]
Just ran into the same issue. Solved it by downgrading `pandas` to `1.1.x`.
No need to change `rb` to `r`; also, `r` probably wouldn't work with compressed CSV files.

**Comment by GitDjTHU** [comment]
> Just ran into the same issue. Solved it by downgrading `pandas` to `1.1.x`.
> No need to change `rb` to `r`; also, `r` probably wouldn't work with compressed CSV files.

**Comment by GitDjTHU** [comment]
> Just ran into the same issue. Solved it by downgrading `pandas` to `1.1.x`.
> No need to change `rb` to `r`; also, `r` probably wouldn't work with compressed CSV files.

So I suppose this should be a `pandas` incompatible issue?

**Comment by wennanzhu** [comment]
Hi @GitDjTHU , does it solve your issue by changing pandas version?

**Comment by zcharles8** [comment]
@alshedivat Do you happen to know which version of `pandas` lead to an error?

**Comment by alshedivat** [comment]
@zcharles8, I think `pandas>=1.2.0` leads to an error.

**Comment by GitDjTHU** [comment]
> Hi @GitDjTHU , does it solve your issue by changing pandas version?

This surely helps so far.

**Comment by zcharles8** [comment]
@GitDjTHU @alshedivat The commit above should have resolved the issue. Please let me know if errors persist, and for which `numpy` versions.
