### ISSUE TITLE
Privacy Analysis of DP-FTRL

### ISSUE THREAD

**Issue by JohnlNguyen** [google-research/federated#30]
![Screen Shot 2021-03-22 at 12 28 03 PM](https://user-images.githubusercontent.com/14943751/112047091-0d0fb880-8b0a-11eb-8fd2-f7d4478e186a.png)

From what I understand, the privacy analysis depends on the tree aggregation protocol and the noise addition from such. 

On line 7 of the algorithm above, would the privacy analysis still holds if we change from an FTRL update to a standard SGD update rule?

**Comment by kairouzp** [comment]
The privacy guarantees would hold but it wouldn't make sense to get the prefix sum and then plug it into a standard SGD update rule. This will likely not give you a meaningful updated model. Please take a look at Section B.3 of https://arxiv.org/pdf/2103.00039.pdf (page 16). Theorem B.1 shows how you can make DP-SGD equivalent to DP-FTRL by appropriately setting the parameters of DP-SGD. Please take a look and let me know if this addresses your concern.
