### ISSUE TITLE
`dataset.reduce` error in Multi-GPU simulation of `optimization`

### ISSUE THREAD

**Issue by hongliny** [google-research/federated#32]
Hi there,

I am trying to launch a multi-gpu experiments based on research/optimization, but keeps getting errors involving `datasets.reduce` as below

```
ValueError: Detected dataset reduce op in multi-GPU TFF simulation: `use_experimental_simulation_loop=True` for `tff.learning`; or use `for ... in iter(dataset)` for your own dataset iteration.Reduce op will be functional after b/159180073.
```

I tried to replace [this line](https://github.com/google-research/federated/blob/c573626cf1698ecf00f50d208da732fc01f88b41/optimization/shared/fed_avg_schedule.py#L172) and [this line](https://github.com/google-research/federated/blob/c573626cf1698ecf00f50d208da732fc01f88b41/optimization/shared/fed_avg_client_opt.py#L245) with `for batch in iter(dataset)`, but the issue persists. I couldn't find any other potential usage of `dataset.reduce`.

Here is the prompt I used to reproduce this issue
```
bazel run main:federated_trainer -- --task=emnist_cr --total_rounds=100 \
--client_optimizer=sgd --client_learning_rate=0.1 --client_batch_size=20 \
--server_optimizer=sgd --server_learning_rate=1.0 --clients_per_round=10 \
--client_epochs_per_round=1 --experiment_name=emnist_fedavg_experiment \
```

Any help will be greatly appreciated.

**Comment by hongliny** [comment]
I find out the solution: the `tff.learning.build_federated_evaluation(tff_model_fn)` should also be replaced with `tff.learning.build_federated_evaluation(tff_model_fn, use_experimental_simulation_loop=True)`.

Closing this issue.

**Comment by hongliny** [comment]
see also https://github.com/google-research/federated/pull/33

**Comment by zcharles8** [comment]
Re-opening for posterity while issues with #33 are being investigated.

**Comment by amitport** [comment]
I'm not sure if this is the same issue, but even when using the built-in `tff.learning.build_federated_evaluation(..., use_experimental_simulation_loop=True)` and `tff.learning.build_federated_averaging_process(..., use_experimental_simulation_loop=True)` I'm getting the following in multi-gpu setup:

```
ValueError: Detected dataset reduce op in multi-GPU TFF simulation: `use_experimental_simulation_loop=True` for `tff.learning`; or use `for ... in iter(dataset)` for your own dataset iteration.Reduce op will be functional after b/159180073.
```

(specifically, I just added those flags `compression\run_experiment.py` and tried to run it as-is)

**Comment by nightldj** [comment]
We seem to have a good understanding about what is happening. In short, in multi-GPU environment, use `experimental_simulation_loop=True` for `tff.learning` functions, and `for...iter(dataset)` for your customized training loops. Note that dropout and layers have internal randomness may sometimes give unexpected results and should be used with care. Closing this issue for now.
