### ISSUE TITLE
Number of client of mnist dataset

### ISSUE THREAD

**Issue by codaibk** [google-research/federated#37]
Hi,
Could you tell me which parameter to set the number of client in mnist dataset? 
in `emnist_dataset_test.py,` That's varibale `TOTAL_NUM_CLIENTS`,  But in `emnist_dataset_test.py`,  I didn't see any variable to set the number of client value.
Thanks.

**Comment by zcharles8** [comment]
Hi @codaibk. `emnist_dataset.py` is derived from the TFF EMNIST dataset (https://www.tensorflow.org/federated/api_docs/python/tff/simulation/datasets/emnist/load_data), which does not let you vary the number of clients (other than by changing whether you use only numeric labels, or alphanumeric). The `TOTAL_NUM_CLIENTS` constant there looks like simply a helper constant from some now removed tests.

If you'd like to run experiments on EMNIST with varying number of clients, you might check out https://github.com/google-research/federated/blob/master/utils/datasets/infinite_emnist.py.
