### ISSUE TITLE
avoid 'tf.io.gfile.glob' in CheckpointManager 

### ISSUE THREAD

**Issue by amitport** [google-research/federated#4]
please avoid using `tf.io.gfile.glob` since https://github.com/tensorflow/tensorflow/issues/19378 issue is causing problems on windows
see https://github.com/google-research/federated/pull/1#issuecomment-702957160

**Comment by zcharles8** [comment]
This is now resolved by https://github.com/google-research/federated/commit/d4a5564e33830b3d6a0ac062ed74d75f55a80872. Thanks for your help.

**Comment by zcharles8** [comment]
I know have permission to close issues, so I will go ahead and resolve this.
