### ISSUE TITLE
The binaries mentioned in Adaptive Learning Rate Decay folder are not available

### ISSUE THREAD

**Issue by pranavgundewar** [google-research/federated#40]
As mentioned, I am unable to find scripts mentioned in following path

![image](https://user-images.githubusercontent.com/37206432/128271707-9e6fed39-f0ac-445f-ac26-e830921fd32a.png)
It gives error 404

**Comment by zcharles8** [comment]
It seems that the README was not updated to reflect a change that consolidated the binaries into a single flag-based binary. I've updated the readme (commit 88c21180dca8d4ea531ce6b4fd344dcde8012839) to reflect this change. Thanks for the heads up!
