### ISSUE TITLE
Question on the Implementation of FedYOGI

### ISSUE THREAD

**Issue by SamuelGong** [google-research/federated#41]
When `self._beta1` is non-zero, 
https://github.com/google-research/federated/blob/f9460d2e92416d487989d4b0b374807a3a42bfec/utils/optimizers/yogi.py#L171
shouldn't  `grad2` be the square of `m_t` instead of `grad`? I am referring to Line 2 of Algorithm2 (Page 4) in Google's [Adaptive Federated Optimization paper](https://arxiv.org/pdf/2003.00295.pdf).

**Comment by zcharles8** [comment]
Hi @SamuelGong. I believe you have identified a slight typo in Algorithm 2 of that work. If you look at the original paper on [Yogi](https://papers.nips.cc/paper/2018/file/90365351ccc7437a1309dc64e4db32a3-Paper.pdf), the gradient (not the momentum-incorporated update) is what is squared. This is also what is used in the implementation.

In the "Adaptive Federated Optimization" paper, it should be clarified that the momentum-weighted update (Line 10) is only used in Line 14. Thanks for catching that. I'll upload a new version of the arXiv paper ASAP.
