### ISSUE TITLE
Issues of federated-gans

### ISSUE THREAD

**Issue by wangclin** [google-research/federated#44]
pip install absl-py
pip install attr
pip install dm-tree
pip install numpy
pip install Pillow
pip install tensorboard
pip install tensorflow
pip install tensorflow-federated
pip install tensorflow-gan
pip install tensorflow-privacy

could you please give a requirement doc or specific version of each library?

I met a lot of version issues about tensorflow and others.

Thanks.

**Comment by nightldj** [comment]
Close this for now. Feel free to re-open if the problem is not solved.
