### ISSUE TITLE
On Dirichlet Concentration Factor

### ISSUE THREAD

**Issue by MasterSkepticista** [google-research/federated#51]
Dirichlet `alpha` is the parameter to be given in `np.random.dirichlet`.

According to the code, `alpha = concentration_factor * prior`.

In the paper: [Adaptive Federated Optimization](https://arxiv.org/pdf/2003.00295.pdf), Dirichlet parameter `0.1` is used for CIFAR10.

Does that mean `concentration_factor * prior == 0.1` (wherein `concentration_factor = 1.0` and prior is `0.1` per class, dirichlet alpha is eff. `0.1`)?
Or does it mean `concentration_factor = 0.1` (wherein dirichlet alpha is effectively `0.01` per class for CIFAR10)?

Referencing the line where this equation is applied:
https://github.com/google-research/federated/blob/7e64bfe86bb606fad2ea7bc2a0f8ebdb565546f9/generalization/synthesization/dirichlet.py#L98

**Comment by zcharles8** [comment]
Hi @MasterSkepticista. The code you referenced is not associated to the Adaptive Federated Optimization paper. Could that explain the mismatch?

**Comment by MasterSkepticista** [comment]
Might be the case @zcharles8.

I think this code is associated with your experiments: https://github.com/google-research/federated/blob/f0ff19d0a5020b6623be1de73a6bab48822c182f/utils/datasets/cifar10_dataset.py#L33

Here, `dirichlet_parameter` is passed as a raw value to the generator. It makes sense for this value to be `0.1`. But isn't this in contrast to Hsu et. al.'s method of sampling from `~Dir(alpha * prior)`? 

The code referenced in this message assumes `prior = 1.0` for all classes, while the one I referenced in the previous message internally computes `prior = 0.1` (for CIFAR-10). What am I missing here?

**Comment by zcharles8** [comment]
Hi @MasterSkepticista. This code was not used in the Adaptive Federated Optimization work. That being said, these are two different code snippets, used in two different projects, so there's no reason that they should agree. For Adaptive Federated Optimization, multinomials were sampled from `Dirichlet(0.1)`, with no prior or concentration factor encoded.
