### ISSUE TITLE
Clarification the result of paper "ADAPTIVE FEDERATED OPTIMIZATION"

### ISSUE THREAD

**Issue by pedropgusmao** [google-research/federated#54]
Hi there!
I'm trying to reproduce the CIFAR100 experiments in 'Adaptive Federate Optimization'. It's a great paper.
I was just wondering if the values for `eta` and `eta_l` in Table 8 of https://arxiv.org/pdf/2003.00295.pdf for CIFAR100 are correct or if there's a typo. I was just expecting FedAvg to always have 0 (=log(1)) .

Thanks

**Comment by zcharles8** [comment]
Hi @pedropgusmao, and thank you for the kind words. The FedAvg algorithm in this work is a generalization of the one in the paper by McMahan et al, which corresponds to setting the server learning rate to 1.0. For details on this, see the discussion directly before Algorithm 1. Hope that helps.

**Comment by zcharles8** [comment]
@pedropgusmao I'm going to mark this as resolved. Thanks.
